### ISSUE TITLE
Twist / RO Added to Random Stroker

### ISSUE THREAD

**Issue by Nepenthy** [tnxa/mosa#30]
User Request
Love the app, is the easiest way Ive found to tweak and calibrate OSR2 for my environment. Can the twist / R0 function be added to Random Stroke routines? Random stroker is actually quite good, and is more "consistent" than videos or vam. Twist functions would be very nice. When the OSR2 is working, trying to keep my mouse on the R0 CCW/CW slider is quite challenging.

**Comment by tnxa** [comment]
@Nepenthy - a deploy preview of a first pass is available at https://deploy-preview-32--trymosa.netlify.app/

Please let me know what you think.

**Comment by Nepenthy** [comment]
Works awesome! Thank you so much!
