### ISSUE TITLE
Newest version of Chrome doesn't allow connection to happen.

### ISSUE THREAD

**Issue by gavonmothma** [tnxa/mosa#4]
``index.js:2177 TypeError: Failed to execute 'open' on 'SerialPort': required member baudRate is undefined.
    at _callee3$ (useSerialHook.js:47)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)``

I get this in the Chrome console after clicking Connect, picking my toy, and hitting Connect. I rebooted, cleared out all add-ins, made sure nothing was running, probably a few other things. It didn't work installed locally either. I was able to get around this by installing an older version of Chrome. So it seems pretty evident that Chrome broke some stuff with Version 86.0.4240.75 (Official Build) (64-bit).

**Comment by tnxa** [comment]
Thank you for raising this, I will take a look.

**Comment by tnxa** [comment]
Thanks for flagging this, @gavonmothma - the API to open ports in webserial seems changed so the `port.open()` call now expects `baudRate` instead of `baudrate`.

I will open a PR to address this.
